ALTER TABLE public.refunds
  ADD COLUMN IF NOT EXISTS produto TEXT,
  ADD COLUMN IF NOT EXISTS produto_grupo TEXT,
  ADD COLUMN IF NOT EXISTS pais TEXT,
  ADD COLUMN IF NOT EXISTS metadata JSONB;

ALTER TABLE public.cancellations
  ADD COLUMN IF NOT EXISTS produto TEXT,
  ADD COLUMN IF NOT EXISTS produto_grupo TEXT,
  ADD COLUMN IF NOT EXISTS pais TEXT,
  ADD COLUMN IF NOT EXISTS metadata JSONB;